### PR TITLE
update to 0.69.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Same as #23 but without re-rendering.

### CODE REVIEW

**Comment by pkgw** [comment]
Some C++ compatibility problem on Linux:

```
error: ‘make_unique’ is not a member of ‘std’
```

**Comment by ocefpaf** [comment]
@isuruf is this something easy to fix or should we report it upstream?

**Comment by isuruf** [comment]
`make_unique` being left out in C++11 standard was an oversight. It's a one liner to implement. (See https://herbsutter.com/gotw/_102/) Does the library say they support C++11 or does it say C++14?

**Comment by ocefpaf** [comment]
> Does the library say they support C++11 or does it say C++14?

No idea :-/

**Comment by ocefpaf** [comment]
It looks like it is C++14:

https://poppler.freedesktop.org/

**Comment by pkgw** [comment]
Superseded by #25.

**Pull request closed without merging**
