### PR TITLE
Update to v22.04.0

### LINKED ISSUE #126: Triggering bot update?
### Comment:

Hi there,

How do we go about triggering the bot to make an update PR?
Poppler is currently on 22.04, whilst this repo is still on 22.01.

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #126

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, @pkgw or @xhochy, you all have more experience with this package than me, I think.  Could you verify that no dependencies need to change?

**Comment by xylar** [comment]
Error for OSX:
```
[198/258] Generating poppler-enums.h
FAILED: glib/poppler-enums.h $SRC_DIR/build/glib/poppler-enums.h 
cd $SRC_DIR/glib && $PREFIX/bin/python3 $PREFIX/bin/glib-mkenums --template poppler-enums.h.template poppler-action.h poppler-date.h poppler-document.h poppler-page.h poppler-attachment.h poppler-form-field.h poppler-annot.h poppler-layer.h poppler-movie.h poppler-media.h poppler.h poppler-structure-element.h > $SRC_DIR/build/glib/poppler-enums.h
/bin/sh: $PREFIX/bin/python3: Bad CPU type in executable

```

For Windows, it looks like a patch needs either to be fixed or removed.

**Comment by pkgw** [comment]
OK, I've pushed some commits that attempt to fix the build issues. It looks like upstream has integrated some patches that aim to fix the MSVC/GooString/std::string C++ cross-library symbol clashing problem — we should test that the resulting artifacts are still OK from that standpoint. I am not sure if there's an easier way to do that than running a custom GDAL build, though.

**Comment by pkgw** [comment]
I can get a Windows package to compile but I'm failing to build GDAL downstream, for reasons that look like they're related to the C++ string stuff:

```
frmts\pdf\pdfdataset.cpp(4329):
error C2664: 'PDFDoc::PDFDoc(void)': cannot convert argument 1 from 'VSIPDFFileStream *' to 'std::unique_ptr<GooString,std::default_delete<_Ty>> &&'
note: Reason: cannot convert from 'VSIPDFFileStream *' to 'std::unique_ptr<GooString,std::default_delete<_Ty>>'
note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

**Comment by pkgw** [comment]
OK, actually, I think that my hacked gdal build was actually misconfigured before. I tried again and the PDF stuff seems to have worked — I ran into a build failure relating to `libblosc` and `libzstd` but I don't think it has anything to do with Poppler.

@conda-forge/poppler anyone else want to look this over?

**Review by xhochy — APPROVED** [review]
Looks good

**Comment by xylar** [comment]
Thanks @pkgw.  Merge when you're ready

**Pull request merged**
