### PR TITLE
Add Cairo Support Windows

### PR DESCRIPTION
**Pull request by oschwartz10612**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempt fix of #66

### CODE REVIEW

**Comment by pkgw** [comment]
Ah, there's a real build error here:

```
.\utils\pdftocairo.cc(890): error C3861: 'strcasecmp': identifier not found
```

The Windows version of libc is different than the standard glibc and, for instance, does not provide this particular function.

This individual issue could be fixable by patching the `pdftocairo.cc` file. This error is a warning sign, though, that the program probably isn't designed to run on Windows, so other issues might crop up. Once again it's hard to know how much of a challenge it will be without plunging in and seeing how things progress.

**Comment by oschwartz10612** [comment]
Okay I will investigate. Thanks.

`pdftocario` was built in [older versions](https://blog.alivate.com.au/poppler-windows/) so theoretically it is possible. We will see.

**Comment by oschwartz10612** [comment]
Whoops! This drives me crazy constantly. Good catch.

Glad that it builds. Didn't have confidence there for a bit.

**Comment by oschwartz10612** [comment]
Do I need to rerender? I am still a bit confused about how that differs from the CI/CD?

**Comment by pkgw** [comment]
@oschwartz10612 The "rerender" process uses automated tools to update the support files in the feedstock repo to track the evolution in the conda-forge infrastructure and guidelines. The CI/CD processes actually execute the recipe and build the packages.

The intention is that it should never hurt to rerender, and the tool will gracefully bow out if there's nothing to do. So, might as well.

**Comment by pkgw** [comment]
@conda-forge-admin, please rerender

**Comment by oschwartz10612** [comment]
Ahh. Thanks for the clarification.

**Comment by oschwartz10612** [comment]
Ready to merge?

**Pull request merged**
