### PR TITLE
Rebuild for latest fontconfig changes

### PR DESCRIPTION
**Pull request by xylar**
Add @xylar as a maintainer.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
We're seeing issues in:
https://github.com/conda-forge/gdal-feedstock/pull/611
That seem related to:
https://github.com/conda-forge/fontconfig-feedstock/pull/53

It seems like (https://github.com/conda-forge/fontconfig-feedstock/pull/53#issuecomment-1062486868) the easiest solution is to rebuild packages that depend on `fontconfig` to bring in these changes.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, @xhochy and @pkgw, I wanted to check with you whether you think a rebuild is all that's needed here to bring in https://github.com/conda-forge/fontconfig-feedstock/pull/53.  CI hasn't finished yet but I figured it wouldn't hurt to get your sense of it before it does.

I added myself as a maintainer but I tend not to be particularly helpful for non-python feedstocks so I would be happy to take myself off the list if you prefer, no hard feelings for sure.

**Comment by pkgw** [comment]
Yes, I believe that a rebuild is all that's needed, but I see that the mac builds here are failing because `cairo` needs to be rebuilt first. So (cf. the other thread) if we'd rather rebuild dependers than patch the macOS package, it looks like a migration would definitely be the way to go.

**Comment by xylar** [comment]
I'm definitely in favor of a migrator but maybe we want to get `gdal` working again faster than a migrator would allow for.

**Comment by pkgw** [comment]
Cairo is now merged. Will have to wait a couple of hours for the builds to finish and propagate, but hopefully this build will work after that happens.

**Comment by xylar** [comment]
The new `cairo` package should now be available.  Let's see what happens.

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
Thanks again, @pkgw and @zklaus

**Comment by zklaus** [comment]
Cheers @xylar. Thanks for the quick fix.

**Pull request merged**
