### PR TITLE
Poppler 21.01.0

### PR DESCRIPTION
**Pull request by oschwartz10612**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oschwartz10612** [comment]
@conda-forge-admin, please rerender

**Comment by oschwartz10612** [comment]
[This](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=265668&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1933) seems to be the issue but this is not my area of expertise.

**Comment by pkgw** [comment]
Windows:

```
..\utils\pdftocairo.cc(392): error C3861: 'setmode': identifier not found
```

No clear error message in the Travis CI logs?

**Comment by oschwartz10612** [comment]
Not sure. Seems to end on `[220/234] Creating library symlink cpp/libpoppler-cpp.so.0 cpp/libpoppler-cpp.so` with some warnings but no errors?

I am probably missing something; I am still learning this sort of thing. Apologies I could not be of more help.

**Comment by pkgw** [comment]
The `setmode` seems to be a recent change:

https://github.com/freedesktop/poppler/commit/928df1f3cf1184e802d07ae444bc11ee084edadd

but I think it's not fully correct, as per this SX answer:

https://stackoverflow.com/a/50419489/3760486

(Note that the other answers to this question are off-base!)

**Comment by pkgw** [comment]
mentioned this upstream: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1029

**Comment by pkgw** [comment]
@conda-forge-admin please restart ci

**Comment by oschwartz10612** [comment]
Thanks for all the help! This has been a great learning experience for me!

**Pull request merged**
