### PR TITLE
Poppler 21.08.0

### PR DESCRIPTION
**Pull request by oschwartz10612**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oschwartz10612** [comment]
@conda-forge-admin, please rerender

**Comment by oschwartz10612** [comment]
It seems that the `exportsymbols` patch might be failing. I will try to redo this.

**Comment by oschwartz10612** [comment]
I will review this over the weekend.

**Comment by Fdawgs** [comment]
Any thoughts on how to resolve this @oschwartz10612?

**Comment by oschwartz10612** [comment]
Sorry I ended up putting this on the back burner.

Forgive me if I am stating the obvious, but the errors are link errors saying that something is in a violation of the one definition rule in poppler-image.cpp. I haven't figured out what or why yet.

I am guessing this is an issue with the patches because why would something be defined more than once in source? It seems like they would catch that when they tried to build? I just dont understand where the connection to `poppler-image.cpp` is yet.

**Comment by pkgw** [comment]
@oschwartz10612 I think that the issue is a bit gnarlier than what's dealt with in the patches, because the things that are being defined multiply seem to be C++ STL symbols, not symbols that are specific to Poppler. From my searching on the C4251 warning, it seems to have to do with STL exports in DLLs, so I think there's probably a connection.

**Comment by silkfire** [comment]
FYI 21.05.0 was released last week, hopefully we can resolve both versions soon.

**Comment by Belval** [comment]
Hi! Any update on this issue? There was a bug in 21.03.0 that we know is fixed in 21.08.0 with TIFF conversion. I'd be willing to have a look but I am not familiar with conda's tooling.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@Belval You could try and open a new PR with the version and sha256 adjusted in `recipe/meta.yaml` starting out from the content of this PR and then we can see how far we get.

**Comment by pkgw** [comment]
I've updated this PR to 21.08.0 just to see where we're at. Had to add Boost as a dependency, and I added in the optional LCMS2 since conda-forge now provides it on all platforms.

**Comment by pkgw** [comment]
OK, the Windows errors didn't magically fix themselves with 21.08.0, but everything else is at least passing ...

**Comment by pkgw** [comment]
OK, I have looked into this some more and I think that the Windows error will be hard to fix. This article seems the most pertinent, I think?:

https://www.cnblogs.com/zhangyz/articles/6238841.html

But the error happens in the poppler-cpp library and we can just ... turn that off. Maybe. Are there Windows users of Poppler that need poppler-cpp?

I've pushed a commit that disables it to see if it builds, but if someone needs the library, we'll have to find another solution.

**Comment by pkgw** [comment]
The Poppler group does have Windows MSVC builds that include poppler-cpp and build fine:

https://ci.appveyor.com/project/tsdgeos/poppler-mirror

Would be nice to understand why those work and ours don't. We have some local patches that futz with dllexport type things? They're on MSVC 2019 but I can reproduce the conda build failure on my own machine using that version.

**Comment by oschwartz10612** [comment]
Finally it builds! Great work! I dont know if my opinion matters or makes any sense, but it might be good to get a build out; it has been a while and it will fix some of the tiff problems on @Belval's end. It does not appear that poppler-cpp is super critical (especially for a Python based community). It can always be worked on in the background for the next release.

P.S. apologies for my lack of contributions. I have been inordinately busy with work this past couple of months.

**Comment by pkgw** [comment]
My perspective is about the same as that of @oschwartz10612 . @conda-forge/poppler folks, any objections to going ahead with this update and leaving the tidying-up until the nebulous Later? Seeing as there hasn't been a ton of traffic on this front overall, I'll plan to merge this around 24 hr from now unless there's more discussion to be had.

**Comment by xhochy** [comment]
The linking error indicates that we probably link to two different runtimes on Windows. For that it would be nice to see the link command or check whether they have changed the default runtime for Windows upstream since the last working release.

**Comment by pkgw** [comment]
@xhochy Do you think we should hold off on merging? Unfortunately I am not at all familiar with the details of how these things work on Windows, although I can at least run a custom build if something would be helpful.

I filed a merge request with upstream to try to integrate some of our more straightforward patches:

https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/901

**Comment by xhochy** [comment]
I'm without a laptop until next week but it would be helpful to have a Windows build with `ninja -v` to see the linker command. This would hopefully be quite enlightening (for me) whether it is the runtime library issue.

**Comment by pkgw** [comment]
The failed builds in our CI do print out the link command. The most recent failure in this PR is, with some linewrapping:

```
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe 
/nologo 
cpp\CMakeFiles\poppler-cpp.dir\poppler-destination.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-document.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-embedded-file.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-font.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-global.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-image.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-page.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-page-renderer.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-page-transition.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-private.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-rectangle.cpp.obj 
cpp\CMakeFiles\poppler-cpp.dir\poppler-toc.cpp.obj
cpp\CMakeFiles\poppler-cpp.dir\poppler-version.cpp.obj
/out:cpp\poppler-cpp.dll 
/implib:cpp\poppler-cpp.lib 
/pdb:cpp\poppler-cpp.pdb 
/dll 
/version:0.9 
/machine:x64 
/INCREMENTAL:NO 
poppler.lib 
%PREFIX%\Library\lib\iconv.lib 
kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib 
/MANIFEST 
/MANIFESTFILE:cpp\poppler-cpp.dll.manifest
```

Again, I don't really know what I'm looking at, but I don't see anything there that obviously has to do with selecting the runtime?

I tried running a verbose build to get the link line used to generate `poppler.dll`, but unfortunately CMake uses a temporary `@response` file for most of the arguments.

**Comment by pkgw** [comment]
Oh hey, from the patch of https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/672, in `cpp/CMakeLists.txt`:

```
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    # Both poppler and poppler-cpp export a class extending std::string (GooString and poppler::ustring)
    # Adding `/FORCE:MULTIPLE` avoids the following link error:
    # `LNK2005 "public: class std::basic_string<char, ...>::assign(...)" already defined in poppler-image.obj`
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /FORCE:MULTIPLE")
endif()
```

Let me see if that works for us ...

**Comment by pkgw** [comment]
Updated to build poppler-cpp on Windows, using this `/FORCE:MULTIPLE` flag to avoid the link errors. Seems to work!

**Comment by pkgw** [comment]
@xhochy Any issues with this new approach? I'd like to merge soon if not!

**Review by xhochy — APPROVED** [review]
Fine with me

**Comment by pkgw** [comment]
Well that took a bit longer than hoped, but so it goes. Thanks for everyone's patience and assistance!

**Pull request merged**
