### PR TITLE
Disable libtiff Win32 I/O

### LINKED ISSUE #73: Empty file while creating Tiff-files from PDF
It seems that when trying to convert to tiff on Windows, a empty tiff file is returned. More information can be found here. 

https://github.com/oschwartz10612/poppler-windows/issues/5

This was tested on my "packaged" version and the real conda package.

### PR DESCRIPTION
**Pull request by kmilos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Resolves #73

### CODE REVIEW

**Comment by pkgw** [comment]
I restarted the Travis build and it failed again with some kind of crash ... but Azure is building macOS too, so I think we should be able to remove the Travis build anyway. I need to jog my memory about how to do that.

**Comment by pkgw** [comment]
Can confirm that this fixes #73!

**Comment by kmilos** [comment]
Great, thanks for testing!

**Review by pkgw — APPROVED** [review]
Works in my local testing!

**Comment by xhochy** [comment]
Can we use cross-compilation instead of emulation? That should be much much faster.

**Comment by pkgw** [comment]
@xhochy I don't know but we could try. How is that enabled?

**Comment by xhochy** [comment]
Have a look at how `osx-arm64` works or how I enabled it in `glib` in https://github.com/conda-forge/glib-feedstock/pull/83/commits/49a2696a56f2088099d2b22f43dd2bff965095ae

**Comment by xhochy** [comment]
Github didn't want to let me add a code suggestion to that file :(

**Comment by pkgw** [comment]
@xhochy Thanks! Testing in a separate PR.

**Comment by pkgw** [comment]
Hmm, aarch64 didn't work, and I don't really want to go down the rabbit-hole of trying to solve that stuff right now, so I'll merge this PR as-is.

**Pull request merged**
