### PR TITLE
add Windows build for v0.67

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Port of #35 to `v0.67.0` branch

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Thanks @gillins! This is awesome!! I guess that the next step is to use this with `gdal`?

**Comment by gillins** [comment]
> I guess that the next step is to use this with gdal?

Indeed! Feel free to have a go, otherwise I can have a look tomorrow

**Comment by ocefpaf** [comment]
I'll take a look but I probably won't be able to get to it today. (Trying to fix ESMF for the new compilers.)

**Pull request merged**
