### PR TITLE
build version 0.65.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Should retarget this to a new branch

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

@jayfurmanek @conda-forge/poppler can somebody please create a new branch for 0.65?

**Comment by pkgw** [comment]
@hmaarrfk Just for reference, what's the motivation here?

**Comment by jayfurmanek** [comment]
We're trying to build some dependencies needed by `r-base` one of which is `texlive-core`. The current version of texlive in the package is 2018 and that only works with an older poppler version. Even `0.65` still needs a patch. The texlive package would need some rework and likely a move up to 2019 (at least) to function with poppler `0.80`.  The idea here is to build the older versions to avoid having to rework that package.

**Comment by hmaarrfk** [comment]
This needs some build number consistency check as well.

I mostly wanted to prove that the old recipe still holds

**Comment by hmaarrfk** [comment]
Should I build 0.64 instead?

**Comment by jayfurmanek** [comment]
The patch for `texlive-core` works against 0.64 or 0.65. This should be good.

**Comment by hmaarrfk** [comment]
This is the last commit to have used 0.65

https://github.com/conda-forge/poppler-feedstock/tree/24ccec08cd03a75d92d585fc9276e06b75930fd4

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
It seems that 0.65 never got built
https://anaconda.org/conda-forge/poppler/files?page=2

This build number is ready to go.

If somebody wanted to create a branch, I would gladly retarget the PR to that branch.

**Comment by hmaarrfk** [comment]
Thanks1

**Pull request merged**
