### PR TITLE
Replace qt with qt-main

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR updates the recipe to depend on the new `qt-main` package instead of the old full `qt`.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by pkgw** [comment]
Thanks for looking at this. I have a couple of questions just because I'm not familiar with some of the context here:

- Should this change be done on a branch or as some kind of migration? I.e. if we switch to `qt-main` are we suddenly incompatible with packages that still require `qt`?
- What's the reason for pinning the specific verrsion of `sysroot_linux-64`?

**Comment by pkgw** [comment]
Thanks for the details. A migration like this is always going to require a "leap of faith" at some point, so I'll trust your judgment about whether now is a good time to move this package to `qt-main` or whether it can/should wait a little while. Should I merge now?

**Comment by izahn** [comment]
After thinking it over and looking at other discussions around this issue I think we should wait for https://github.com/conda-forge/staged-recipes/pull/17233 which will hopefully be ready soon.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Superseded by https://github.com/conda-forge/poppler-feedstock/pull/128

**Pull request closed without merging**
